version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  server:
    build:
      context: ./server
      dockerfile: ../docker/Dockerfile.server
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/myapp
      - PORT=3000

  client:
    build:
      context: ./client
      dockerfile: ../docker/Dockerfile.client
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  mongodb_data:
