name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install client dependencies
        run: |
          cd client
          npm install
          npm run build

      - name: Install server dependencies
        run: |
          cd server
          npm install
          npm run build

      - name: Run client tests
        run: |
          cd client
          npm test

      - name: Run server tests
        run: |
          cd server
          npm test
